name: Deploy to Production Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Deploy Application
        run: |
          SSH_USER="root"
          SSH_HOST="188.34.158.27"
          DEPLOY_PATH="/var/www/Lexi"
          
          # Add host key
          ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
          
          # Deploy via Git pull (efficiënter dan zip/unzip)
          ssh $SSH_USER@$SSH_HOST "
            cd $DEPLOY_PATH
            
            # Pull latest changes
            git pull origin main
            
            # Set up Node environment
            export PATH=/root/.nvm/versions/node/v22.20.0/bin:\$PATH
            
            # Load environment variables
            export \$(grep -v '^#' .env | xargs) 2>/dev/null || true
            
            # Install dependencies and build
            npm install
            npm run build
            
            # Restart PM2
            pm2 delete Lexi 2>/dev/null || true
            pm2 start --name 'Lexi' main.py --interpreter python3
            pm2 save
          "
